### ISSUE TITLE
There is a problem when install it on laravel 9 

### ISSUE THREAD

**Issue by mahmoudAkobah** [laravel-notification-channels/google-chat#10]
Is this package support laravel 9, because I try to install it on fresh laravel 9 but return this error 

Problem 1
    - Root composer.json requires laravel-notification-channels/google-chat ^2.0 -> satisfiable by laravel-notification-channels/google-chat[v2.0.0].
    - laravel-notification-channels/google-chat v2.0.0 requires illuminate/notifications ~9.0.2 -> found illuminate/notifications[v9.0.2] but these were not loaded, likely because it conflicts with another require.

![Screenshot from 2022-02-22 09-05-29](https://user-images.githubusercontent.com/53005040/155080196-2c300e6c-665e-4714-b878-b86e5c04c4e2.png)

**Comment by frankieeedeee** [comment]
Thanks for flagging @mahmoudAkobah!

This has now been resolved in #12 and version `2.0.1` of the package :)
