### ISSUE TITLE
Failed to send Google Chat message

### ISSUE THREAD

**Issue by mahmoudmohamedramadan** [laravel-notification-channels/google-chat#3]
I've installed this package and create a new Google Chat Room called `Laravel`, and edit the `spaces` key in the `google-chat.php` config file to be as the following
```PHP
'laravel_google_chat' => 'https://chat.googleapis.com/laravel?key='
```
also, I've created a controller called `UserController.php` WITH only one function as the following
```PHP
public function notifyUserViaGoogleChat()
{
     User::find(1)
              ->notify(new GoogleChatNotification);
}
```

and in `GoogleChatNotification.php` , I've put this code inside `via` mehod
```php
public function via($notifiable)
{
    return [
         GoogleChatChannel::class
    ];
}
```

and in the `toGoogleChat` method, I've put the following code
```PHP
public function toGoogleChat($notifiable)
{
    return GoogleChatMessage::create('An invoice was paid!')
                      ->to('laravel_google_chat');
}
```

and FINALLY, in the `web.php` routes file I've put this line of code
```PHP
Route::get('notifyUser', [UserController::class, 'notifyUserViaGoogleChat']);
```

BUT when I visit this route, an error happens  `Failed to send Google Chat message, encountered client error: `404 - Client error: `POST https://chat.googleapis.com/laravel?key= resulted in a 404 Not Found response: <h1>Not Found</h1> <h2>Error 404</h2> `

**Comment by frankieeedeee** [comment]
Hey @mahmoudmohamedramadan Looks like there might be an issue with the webhook URL you've configured. Did you copy this exactly from the webhooks setting pane within Google Chat?

URLs generated have the form of `https://chat.googleapis.com/v1/rooms/{SECRET}`

Cheers!
