### ISSUE TITLE
Nothing happens?

### ISSUE THREAD

**Issue by lukasmedia** [laravel-notification-channels/google-chat#8]
Hi,

I did as instructed by the readme. Composer, google-chat config, default room/space, one extra room/space (and ofcourse created webhooks).

When i try:

GoogleChatMessage::create('Hello world!');

Nothing happens.

When i paste URL in browser:

https://chat.googleapis.com/v1/spaces/xxxxxxxx/messages?key=yyyyyy&token=zzz={%22text%22:%20%22New%20Relic%20Test%22}

{
  "error": {
    "code": 401,
    "message": "API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication",
    "status": "UNAUTHENTICATED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "CREDENTIALS_MISSING",
        "domain": "googleapis.com",
        "metadata": {
          "service": "chat.googleapis.com",
          "method": "google.chat.v1.ChatService.InvalidGetPath"
        }
      }
    ]
  }
}

**Comment by frankieeedeee** [comment]
Hi @lukasmedia Would recommend checking out the [Laravel documentation for notifications](https://laravel.com/docs/8.x/notifications), which describes how to create a Notification object that builds and returns a `GoogleChatMessage` object.

Calling `GoogleChatMessage::create(...)` will simply generate the structure and content of your notification, but will not deliver it. You'll need to reference 

Additionally, not too sure what you're trying to accomplish there by pasting the URL in the browser? Seems unrelated to this package, particularly given that creating Google Chat messages require a HTTP POST request, not a GET request (which is what pasting a URL in your browser is doing).

Feel free to comment/re-open if I've missed something - Cheers! 🙂

**Comment by lukasmedia** [comment]
Hi @frankieeedeee thanks!
